# Generated by Django 5.0.6 on 2024-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('sellPrice', models.PositiveBigIntegerField()),
                ('rentPrice', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
