# Generated by Django 5.0.6 on 2024-07-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='land',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='land.land'),
        ),
    ]
