# Generated by Django 5.0.6 on 2024-07-10 09:33

import django.db.models.deletion
import iranian_cities.fields
import land.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('address', models.CharField(max_length=750)),
                ('areaOfBuilding', models.FloatField(blank=True, null=True)),
                ('areaOfLand', models.FloatField()),
                ('electricityAmper', models.FloatField(blank=True, null=True)),
                ('edari', models.CharField(blank=True, max_length=255, null=True)),
                ('buildingHeight', models.FloatField(blank=True, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('secondaryPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ownerName', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=land.models.land_upload_path)),
                ('privetNote', models.TextField(blank=True, null=True)),
                ('city', iranian_cities.fields.ShahrField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr')),
                ('features', models.ManyToManyField(related_name='lands', to='land.feature')),
                ('province', iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan')),
            ],
        ),
    ]
