# Generated by Django 5.0.6 on 2024-07-10 10:58

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='city',
            field=iranian_cities.fields.ShahrField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr'),
        ),
        migrations.AlterField(
            model_name='land',
            name='province',
            field=iranian_cities.fields.OstanField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan'),
        ),
    ]
