# Generated by Django 5.0.6 on 2024-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_alter_land_city_alter_land_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPropertyUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='land',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='lands', to='land.feature'),
        ),
    ]
