# Generated by Django 5.0.6 on 2024-07-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_alter_land_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='land.status'),
        ),
        migrations.AddField(
            model_name='land',
            name='typeOfPropertyUse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeOfPropertyUse', to='land.typeofpropertyuse'),
        ),
    ]
